// Données de départ du backend OKLA — miroir de src/data.js.
// (Marketing restaurants + liste de Tanger.) Sert d'amorçage au "service" en mémoire.

export const restaurants = [
  { id: 'r1', name: 'Le Jardin Marrakech', cuisine: 'Marocaine · Traditionnelle', rating: 4.6, reviews: 128, time: '25–35 min', price: '€€', tag: 'Populaire', from: '#c9622f', to: '#8f4a2a', img: '/images/jardin-marrakech.jpg' },
  { id: 'r2', name: 'Dar Tajine', cuisine: 'Marocaine · Cuisine du terroir', rating: 4.8, reviews: 212, time: '30–40 min', price: '€€', tag: 'Nouveau', from: '#b9682f', to: '#7d4a26', img: '/images/dar-tajine.jpg' },
  { id: 'r3', name: 'Riad Saveurs', cuisine: 'Méditerranéenne', rating: 4.5, reviews: 96, time: '20–30 min', price: '€€€', tag: '', from: '#cf7b3a', to: '#955a2e', img: '/images/riad-saveurs.jpg' },
  { id: 'r4', name: 'Atlas Grill', cuisine: 'Grillades · Internationale', rating: 4.7, reviews: 154, time: '25–35 min', price: '€€', tag: 'Top noté', from: '#c2632c', to: '#854524', img: '/images/atlas-grill.jpg' },
]

// Restaurants de Tanger (coordonnées x,y sur la carte stylisée 640x520).
// Doit rester identique au tableau `tangier` de src/data.js (repli hors-ligne).
// Menu : { name, desc, price, cat, star? } — `star` = plat incontournable.
// `slots` = créneaux libres · `slotsFull` = créneaux complets (affichés barrés).
export const tangier = [
  {
    id: 't1', hours: '12:00–15:00 et 19:00–23:30', name: 'Le Jardin Marrakech', cuisine: 'Marocaine · Traditionnelle', area: 'Médina',
    rating: 4.8, reviews: 212, price: '€€', priceLevel: 2, offer: '-20%', offerDesc: '−20% sur la carte le midi', availableTonight: true,
    slots: ['19:30','20:00','20:30','21:00'], slotsFull: ['21:30'], x: 300, y: 255, from: '#c9622f', to: '#8f4a2a',
    img: '/images/jardin-marrakech.jpg',
    photos: ['/images/jardin-marrakech.jpg'],
    description: 'Un patio verdoyant au cœur de la Médina, où les tajines mijotent selon les recettes de la grand-mère. Ambiance feutrée et thé à la menthe à volonté.',
    tags: ['Terrasse', 'Romantique', 'Cuisine locale'],
    menu: [
      { name: 'Zaalouk d’aubergines', desc: 'Caviar d’aubergines fumées au cumin et huile d’olive', price: '35 DH', cat: 'Entrées' },
      { name: 'Briouates au fromage', desc: 'Feuilletés croustillants au fromage frais, miel et sésame doré', price: '45 DH', cat: 'Entrées' },
      { name: 'Tajine d’agneau aux pruneaux', desc: 'Agneau fondant mijoté aux pruneaux, amandes et cannelle', price: '95 DH', cat: 'Plats', star: true },
      { name: 'Pastilla au poulet', desc: 'Feuille croustillante, poulet aux amandes et sucre glace', price: '90 DH', cat: 'Plats', star: true },
      { name: 'Couscous royal', desc: 'Semoule fine, légumes du marché et trois viandes, le vendredi', price: '110 DH', cat: 'Plats', star: true },
      { name: 'Rfissa au poulet beldi', desc: 'Msemen émietté, poulet fermier, lentilles et fenugrec', price: '85 DH', cat: 'Plats' },
      { name: 'Cornes de gazelle', desc: 'Pâte d’amande parfumée à la fleur d’oranger', price: '30 DH', cat: 'Desserts' },
      { name: 'Thé à la menthe', desc: 'Menthe fraîche du Rif, servi à la tangéroise', price: '20 DH', cat: 'Boissons' },
    ],
    reviewList: [
      { name: 'Yasmine B.', rating: 5, text: 'Cadre magnifique et tajine d’agneau fondant. On se croirait à Marrakech.', date: 'il y a 2 j' },
      { name: 'Omar T.', rating: 4, text: 'Service attentionné, un peu d’attente mais ça valait le coup.', date: 'il y a 1 sem.' },
      { name: 'Claire D.', rating: 5, text: 'La pastilla était divine, adresse à retenir.', date: 'il y a 3 sem.' },
    ],
  },
  {
    id: 't2', hours: '12:30–15:30 et 19:30–23:00', name: 'Dar Tajine', cuisine: 'Marocaine · Terroir', area: 'Marshan',
    rating: 4.6, reviews: 128, price: '€€', priceLevel: 2, offer: null, availableTonight: false,
    slots: ['19:00','20:00','21:30'], slotsFull: ['19:30','20:30'], x: 150, y: 235, from: '#b9682f', to: '#7d4a26',
    img: '/images/dar-tajine.jpg',
    photos: ['/images/dar-tajine.jpg'],
    description: 'Maison de famille perchée à Marshan, spécialiste des tajines du terroir cuits au feu de bois. Vue dégagée et accueil chaleureux.',
    tags: ['Vue mer', 'Familial', 'Traditionnel'],
    menu: [
      { name: 'Harira maison', desc: 'Soupe traditionnelle aux lentilles, pois chiches et coriandre fraîche', price: '30 DH', cat: 'Entrées', star: true },
      { name: 'Briouates à la kefta', desc: 'Triangles croustillants à la viande hachée épicée', price: '40 DH', cat: 'Entrées' },
      { name: 'Tajine kefta aux œufs', desc: 'Boulettes de bœuf, sauce tomate épicée et œufs mollets', price: '75 DH', cat: 'Plats', star: true },
      { name: 'Tajine poulet citron confit', desc: 'Poulet beldi, citrons confits maison et olives violettes', price: '85 DH', cat: 'Plats', star: true },
      { name: 'Tajine de légumes du terroir', desc: 'Légumes de saison mijotés au feu de bois', price: '65 DH', cat: 'Plats' },
      { name: 'Couscous tfaya', desc: 'Semoule, oignons caramélisés, raisins secs et pois chiches', price: '95 DH', cat: 'Plats' },
      { name: 'Cornes de gazelle', desc: 'Recette familiale, amande et fleur d’oranger', price: '35 DH', cat: 'Desserts' },
      { name: 'Thé à la menthe du Rif', desc: 'Préparé au charbon, mousse légère', price: '20 DH', cat: 'Boissons' },
    ],
    reviewList: [
      { name: 'Hicham A.', rating: 5, text: 'Le meilleur tajine kefta de Tanger, sans hésiter.', date: 'il y a 4 j' },
      { name: 'Sofia L.', rating: 4, text: 'Portions généreuses et prix tout doux.', date: 'il y a 2 sem.' },
    ],
  },
  {
    id: 't3', hours: '12:00–16:00 et 19:00–00:00', name: 'Saveur de Poisson', cuisine: 'Poisson · Méditerranéenne', area: 'Médina · Port',
    rating: 4.7, reviews: 340, price: '€€', priceLevel: 2, offer: '-30%', offerDesc: '−30% sur le menu du soir', availableTonight: true,
    slots: ['19:30','20:30','21:00'], slotsFull: ['20:00'], x: 372, y: 200, from: '#3f7d86', to: '#2d5a61',
    img: '/images/saveur-poisson.jpg',
    photos: ['/images/saveur-poisson.jpg'],
    description: 'Institution du port : un menu unique de poissons frais du jour servi en cinq services. Décor de bois flotté et jus de fruits maison.',
    tags: ['Poisson frais', 'Convivial', 'Cuisine locale'],
    menu: [
      { name: 'Soupe de poisson', desc: 'Bouillon safrané du port, croûtons et rouille maison', price: '40 DH', cat: 'Entrées', star: true },
      { name: 'Friture de calamars', desc: 'Calamars dorés, citron et sauce chermoula', price: '60 DH', cat: 'Entrées' },
      { name: 'Bar grillé du jour', desc: 'Poisson entier du matin, grillé au charbon, selon arrivage', price: '120 DH', cat: 'Plats', star: true },
      { name: 'Brochettes de crevettes', desc: 'Crevettes royales marinées à l’ail et au persil', price: '95 DH', cat: 'Plats', star: true },
      { name: 'Espadon à la plancha', desc: 'Tranche épaisse, légumes sautés et riz safrané', price: '110 DH', cat: 'Plats' },
      { name: 'Pageot au four', desc: 'Cuit aux pommes de terre, tomates et poivrons, selon arrivage', price: '100 DH', cat: 'Plats' },
      { name: 'Salade de fruits frais', desc: 'Fruits de saison, eau de fleur d’oranger', price: '30 DH', cat: 'Desserts' },
      { name: 'Jus de fruits maison', desc: 'Orange, avocat-lait d’amande ou panaché', price: '25 DH', cat: 'Boissons' },
    ],
    reviewList: [
      { name: 'Mehdi R.', rating: 5, text: 'Expérience inoubliable, tout est frais et copieux.', date: 'il y a 1 j' },
      { name: 'Anaïs P.', rating: 5, text: 'Le bar grillé était parfait. On reviendra !', date: 'il y a 5 j' },
      { name: 'Karim S.', rating: 4, text: 'Cadre simple mais cuisine excellente.', date: 'il y a 2 sem.' },
    ],
  },
  {
    id: 't4', hours: '18:00–01:00', name: 'El Morocco Club', cuisine: 'Internationale · Lounge', area: 'Kasbah',
    rating: 4.5, reviews: 96, price: '€€€', priceLevel: 3, offer: null, availableTonight: true,
    slots: ['20:00','20:30','21:30','22:00'], slotsFull: [], x: 252, y: 182, from: '#6f5a3a', to: '#4a3b25',
    img: '/images/el-morocco.jpg',
    photos: ['/images/el-morocco.jpg'],
    description: 'Élégant lounge de la Kasbah mêlant cuisine internationale et piano-bar. Cocktails signature et terrasse sous les bougainvilliers.',
    tags: ['Lounge', 'Chic', 'Cocktails'],
    menu: [
      { name: 'Tartare de thon rouge', desc: 'Thon du détroit, avocat, sésame et agrumes', price: '130 DH', cat: 'Entrées', star: true },
      { name: 'Burrata crémeuse', desc: 'Tomates anciennes, basilic et huile d’olive de Chefchaouen', price: '95 DH', cat: 'Entrées' },
      { name: 'Risotto aux gambas', desc: 'Riz carnaroli crémeux, gambas snackées, bisque réduite', price: '150 DH', cat: 'Plats', star: true },
      { name: 'Filet de bœuf grillé', desc: 'Sauce au poivre, pommes grenaille et légumes glacés', price: '180 DH', cat: 'Plats', star: true },
      { name: 'Magret de canard laqué', desc: 'Miel d’oranger, purée de patate douce', price: '165 DH', cat: 'Plats' },
      { name: 'Cheesecake aux agrumes', desc: 'Spéculoos, crème citron-orange', price: '60 DH', cat: 'Desserts' },
      { name: 'Mocktail signature', desc: 'Concombre, menthe, gingembre et tonic', price: '55 DH', cat: 'Boissons' },
    ],
    reviewList: [
      { name: 'Leïla M.', rating: 5, text: 'Ambiance raffinée, idéal pour une soirée spéciale.', date: 'il y a 3 j' },
      { name: 'Thomas V.', rating: 4, text: 'Cocktails superbes, cuisine soignée.', date: 'il y a 1 sem.' },
    ],
  },
  {
    id: 't5', hours: '11:30–15:00 et 19:00–22:30', name: 'Riad Saveurs', cuisine: 'Méditerranéenne', area: 'Centre-ville',
    rating: 4.5, reviews: 110, price: '€€', priceLevel: 2, offer: '-20%', offerDesc: '−20% sur le déjeuner en terrasse', availableTonight: true,
    slots: ['12:30','13:00','19:30','20:00'], slotsFull: ['13:30'], x: 340, y: 345, from: '#cf7b3a', to: '#955a2e',
    img: '/images/riad-saveurs.jpg',
    photos: ['/images/riad-saveurs.jpg'],
    description: 'Riad lumineux au centre-ville proposant une carte méditerranéenne fraîche et colorée. Parfait pour un déjeuner ensoleillé.',
    tags: ['Terrasse', 'Healthy', 'Déjeuner'],
    menu: [
      { name: 'Mezze méditerranéen', desc: 'Houmous, zaalouk, taboulé et pain pita tiède', price: '65 DH', cat: 'Entrées', star: true },
      { name: 'Salade César', desc: 'Poulet grillé, parmesan, croûtons à l’ail', price: '55 DH', cat: 'Entrées' },
      { name: 'Linguine aux fruits de mer', desc: 'Crevettes, moules et calamars, sauce tomate-basilic', price: '105 DH', cat: 'Plats', star: true },
      { name: 'Brochette de poulet aux herbes', desc: 'Marinade citron-origan, riz et tzatziki', price: '85 DH', cat: 'Plats' },
      { name: 'Lasagnes de légumes', desc: 'Aubergines, courgettes et ricotta gratinées', price: '80 DH', cat: 'Plats' },
      { name: 'Tiramisu', desc: 'Mascarpone onctueux, café et cacao amer', price: '45 DH', cat: 'Desserts', star: true },
      { name: 'Citronnade à la menthe', desc: 'Pressée minute, miel et menthe fraîche', price: '25 DH', cat: 'Boissons' },
    ],
    reviewList: [
      { name: 'Nadia E.', rating: 4, text: 'Salades créatives et personnel adorable.', date: 'il y a 6 j' },
      { name: 'Paul G.', rating: 5, text: 'Le menu du midi est une excellente affaire.', date: 'il y a 2 sem.' },
    ],
  },
  {
    id: 't6', hours: '12:00–23:30 en continu', name: 'Atlas Grill', cuisine: 'Grillades · Internationale', area: 'Malabata',
    rating: 4.7, reviews: 154, price: '€€', priceLevel: 2, offer: null, availableTonight: false,
    slots: ['19:00','19:30','20:30'], slotsFull: ['20:00','21:00'], x: 492, y: 258, from: '#7a8a3e', to: '#566127',
    img: '/images/atlas-grill.jpg',
    photos: ['/images/atlas-grill.jpg'],
    description: 'Grillades généreuses face à la baie de Malabata : viandes maturées, brochettes et poissons au charbon de bois.',
    tags: ['Grillades', 'Vue mer', 'Familial'],
    menu: [
      { name: 'Salade marocaine', desc: 'Tomates, concombre, oignons et olives concassés', price: '30 DH', cat: 'Entrées' },
      { name: 'Brochettes mixtes', desc: 'Bœuf, poulet et kefta grillés au charbon de bois', price: '90 DH', cat: 'Plats', star: true },
      { name: 'Côte de bœuf (400 g)', desc: 'Maturée 21 jours, frites maison et sauce chimichurri', price: '180 DH', cat: 'Plats', star: true },
      { name: 'Poulet grillé fermier', desc: 'Demi-poulet beldi mariné aux épices, frites', price: '85 DH', cat: 'Plats', star: true },
      { name: 'Côtelettes d’agneau', desc: 'Grillées au thym, légumes du marché', price: '130 DH', cat: 'Plats' },
      { name: 'Merguez de bœuf', desc: 'Épicées, grillées, servies avec pain maison', price: '70 DH', cat: 'Plats' },
      { name: 'Crème caramel', desc: 'Caramel ambré, recette de toujours', price: '35 DH', cat: 'Desserts' },
      { name: 'Thé ou café', desc: 'Pour finir en douceur face à la baie', price: '15 DH', cat: 'Boissons' },
    ],
    reviewList: [
      { name: 'Rachid B.', rating: 5, text: 'Viande tendre et bien assaisonnée, top.', date: 'il y a 2 j' },
      { name: 'Inès F.', rating: 4, text: 'Cadre agréable au bord de l’eau.', date: 'il y a 10 j' },
    ],
  },
  {
    id: 't7', hours: '12:00–15:00 et 19:00–23:00 · fermé le lundi', name: 'Dar Bahia', cuisine: 'Marocaine · Traditionnelle', area: 'Kasbah',
    rating: 4.4, reviews: 187, price: '€€', priceLevel: 2, offer: null, availableTonight: true,
    slots: ['19:30','20:00','21:00'], slotsFull: ['20:30'], x: 218, y: 212, from: '#8a6a3f', to: '#5d4527',
    img: '/images/restaurants/dar-bahia.jpg',
    photos: ['/images/restaurants/dar-bahia.jpg'],
    description: 'Riad du XVIIIᵉ siècle caché dans une ruelle de la Kasbah, célèbre pour sa pastilla au pigeon dorée au four. Patio en zellige, lanternes et calme absolu.',
    tags: ['Traditionnel', 'Romantique', 'Calme', 'Terrasse'],
    menu: [
      { name: 'Harira de la Kasbah', desc: 'Velours de lentilles et tomates, dattes en accompagnement', price: '30 DH', cat: 'Entrées' },
      { name: 'Briouates poulet-amandes', desc: 'Croustillants au poulet fermier, amandes et cannelle', price: '50 DH', cat: 'Entrées' },
      { name: 'Pastilla au pigeon', desc: 'La spécialité maison : pigeon fermier, amandes, dorée au four', price: '140 DH', cat: 'Plats', star: true },
      { name: 'Tajine d’agneau aux artichauts', desc: 'Agneau de lait, artichauts sauvages et petits pois', price: '105 DH', cat: 'Plats' },
      { name: 'Couscous aux sept légumes', desc: 'Semoule d’orge, légumes de saison et bouillon parfumé', price: '100 DH', cat: 'Plats', star: true },
      { name: 'Méchoui d’agneau (sur commande)', desc: 'Épaule confite cinq heures, cumin et fleur de sel', price: '160 DH', cat: 'Plats', star: true },
      { name: 'Sellou maison', desc: 'Amandes, sésame grillé et miel — douceur de la maison', price: '25 DH', cat: 'Desserts' },
      { name: 'Thé à la chiba', desc: 'Thé vert à l’absinthe sauvage, façon Kasbah', price: '20 DH', cat: 'Boissons' },
    ],
    reviewList: [
      { name: 'Salma R.', rating: 5, text: 'La pastilla au pigeon vaut le détour à elle seule. Patio splendide.', date: 'il y a 3 j' },
      { name: 'Julien M.', rating: 4, text: 'Très bon méchoui, service un peu lent en soirée.', date: 'il y a 1 sem.' },
      { name: 'Khadija O.', rating: 4, text: 'Adresse pleine de charme, on s’y sent hors du temps.', date: 'il y a 3 sem.' },
    ],
  },
  {
    id: 't8', hours: '12:00–23:00 en continu', name: 'Marsa Fish', cuisine: 'Poisson · Fruits de mer', area: 'Corniche · Plage',
    rating: 4.3, reviews: 526, price: '€', priceLevel: 1, offer: 'Dessert', offerDesc: 'Dessert offert dès deux plats commandés', availableTonight: true,
    slots: ['13:00','19:00','20:00','21:00'], slotsFull: [], x: 448, y: 176, from: '#4a8893', to: '#31626b',
    img: '/images/restaurants/marsa-fish.jpg',
    photos: ['/images/restaurants/marsa-fish.jpg'],
    description: 'Cabane conviviale les pieds dans le sable, où l’arrivage du port se choisit à la criée avant de passer au gril. Friture dorée et coucher de soleil sur le détroit.',
    tags: ['Poisson frais', 'Familial', 'Terrasse'],
    menu: [
      { name: 'Salade de poulpe', desc: 'Poulpe tendre, pommes de terre et paprika fumé', price: '55 DH', cat: 'Entrées' },
      { name: 'Friture de poisson', desc: 'Petite friture du détroit, citron et pain maison', price: '70 DH', cat: 'Plats', star: true },
      { name: 'Plateau fruits de mer', desc: 'Crevettes, calamars, moules et poisson du jour à partager', price: '180 DH', cat: 'Plats', star: true },
      { name: 'Sardines grillées', desc: 'À la chermoula, comme sur le port', price: '45 DH', cat: 'Plats' },
      { name: 'Crevettes pil-pil', desc: 'Sautées à l’ail et au piment doux, pain frit', price: '85 DH', cat: 'Plats' },
      { name: 'Calamars à la plancha', desc: 'Selon arrivage, huile d’olive citronnée', price: '90 DH', cat: 'Plats' },
      { name: 'Riz aux fruits de mer', desc: 'Façon paella tangéroise, safran et citron', price: '95 DH', cat: 'Plats', star: true },
      { name: 'Salade d’oranges à la cannelle', desc: 'Dessert frais du jour, miel d’oranger', price: '20 DH', cat: 'Desserts' },
    ],
    reviewList: [
      { name: 'Younes K.', rating: 5, text: 'Poisson ultra frais, prix imbattables. L’adresse du dimanche.', date: 'il y a 2 j' },
      { name: 'Marta G.', rating: 4, text: 'Friture excellente, cadre simple mais vue superbe.', date: 'il y a 1 sem.' },
      { name: 'Adil B.', rating: 4, text: 'Le plateau à partager est généreux. Un peu d’attente le week-end.', date: 'il y a 2 sem.' },
    ],
  },
  {
    id: 't9', hours: '19:00–01:00 · fermé le dimanche', name: 'Noor Rooftop', cuisine: 'Fusion · Asiatique', area: 'Bd Pasteur',
    rating: 4.6, reviews: 238, price: '€€€', priceLevel: 3, offer: '-50%', offerDesc: 'Happy hour : −50% sur les mocktails (18h–20h)', availableTonight: true,
    slots: ['20:00','21:00','22:00'], slotsFull: ['20:30','21:30'], x: 395, y: 308, from: '#6b7a3c', to: '#49541f',
    img: '/images/restaurants/noor-rooftop.jpg',
    photos: ['/images/restaurants/noor-rooftop.jpg'],
    description: 'Rooftop branché au-dessus du boulevard Pasteur : sushis aux saveurs marocaines, woks flambés et DJ sets au coucher du soleil. La vue sur le détroit fait le reste.',
    tags: ['Rooftop', 'Branché', 'Cocktails', 'Musique live'],
    menu: [
      { name: 'Gyozas bœuf & ras el hanout', desc: 'Raviolis grillés, bouillon corsé aux épices marocaines', price: '75 DH', cat: 'Entrées' },
      { name: 'Maki chermoula', desc: 'Saumon mariné à la chermoula, avocat et sésame', price: '95 DH', cat: 'Plats', star: true },
      { name: 'Pad thaï au poulet', desc: 'Nouilles de riz sautées, cacahuètes et citron vert', price: '110 DH', cat: 'Plats', star: true },
      { name: 'Wok de bœuf teriyaki', desc: 'Bœuf sauté minute, légumes croquants, riz jasmin', price: '120 DH', cat: 'Plats' },
      { name: 'Bao à la kefta', desc: 'Brioche vapeur, kefta épicée, pickles d’oignons', price: '65 DH', cat: 'Plats' },
      { name: 'Perles coco-mangue', desc: 'Tapioca, lait de coco et mangue fraîche', price: '50 DH', cat: 'Desserts' },
      { name: 'Mocktail Noor', desc: 'Litchi, rose et citron vert — star du happy hour', price: '60 DH', cat: 'Boissons' },
    ],
    reviewList: [
      { name: 'Lina S.', rating: 5, text: 'Vue incroyable au coucher du soleil, makis originaux.', date: 'il y a 1 j' },
      { name: 'Reda A.', rating: 4, text: 'Ambiance top le week-end, pensez à réserver tôt.', date: 'il y a 5 j' },
    ],
  },
  {
    id: 't10', hours: '12:00–15:00 et 19:00–23:30', name: 'Trattoria Gibraltar', cuisine: 'Italienne · Pizzeria', area: 'Centre-ville',
    rating: 4.5, reviews: 342, price: '€€', priceLevel: 2, offer: null, availableTonight: false,
    slots: ['12:30','19:30','21:30'], slotsFull: ['20:00','20:30','21:00'], x: 290, y: 440, from: '#c0552e', to: '#7e3a20',
    img: '/images/restaurants/trattoria-gibraltar.jpg',
    photos: ['/images/restaurants/trattoria-gibraltar.jpg'],
    description: 'Trattoria familiale au four à bois, tenue par un couple italo-tangérois depuis 1998. Pâtes fraîches étirées le matin et pizzas qui sortent en quatre-vingt-dix secondes.',
    tags: ['Familial', 'Branché', 'Convivial', 'Déjeuner'],
    menu: [
      { name: 'Bruschetta tomate-basilic', desc: 'Pain grillé au feu de bois, tomates confites, ail doux', price: '40 DH', cat: 'Entrées' },
      { name: 'Burrata di casa', desc: 'Crème de burrata, roquette et tomates séchées', price: '75 DH', cat: 'Entrées' },
      { name: 'Pizza Margherita', desc: 'Mozzarella fior di latte, basilic, four à bois', price: '75 DH', cat: 'Plats', star: true },
      { name: 'Pizza Gibraltar', desc: 'Thon du détroit, olives noires, câpres et oignons rouges', price: '90 DH', cat: 'Plats', star: true },
      { name: 'Tagliatelle alla bolognese', desc: 'Ragoût de bœuf mijoté six heures', price: '95 DH', cat: 'Plats' },
      { name: 'Risotto aux champignons', desc: 'Carnaroli, champignons et parmesan affiné', price: '100 DH', cat: 'Plats' },
      { name: 'Tiramisu della nonna', desc: 'Le vrai, dressé à la minute', price: '45 DH', cat: 'Desserts', star: true },
      { name: 'Limonade italienne', desc: 'Citron pressé, glace pilée', price: '30 DH', cat: 'Boissons' },
    ],
    reviewList: [
      { name: 'Giulia F.', rating: 5, text: 'La meilleure pizza de Tanger, pâte parfaite.', date: 'il y a 4 j' },
      { name: 'Mounir L.', rating: 4, text: 'Ambiance familiale, portions généreuses.', date: 'il y a 2 sem.' },
      { name: 'Sara D.', rating: 4, text: 'Tiramisu incroyable. Salle vite pleine le soir.', date: 'il y a 3 sem.' },
    ],
  },
  {
    id: 't11', hours: '08:00–20:00', name: 'Café Hafa Vista', cuisine: 'Café · Brunch', area: 'Marshan',
    rating: 4.7, reviews: 904, price: '€', priceLevel: 1, offer: null, availableTonight: false,
    slots: ['09:00','10:30','12:00'], slotsFull: ['11:00'], x: 100, y: 285, from: '#5f9aa0', to: '#3e6d72',
    img: '/images/restaurants/cafe-hafa-vista.jpg',
    photos: ['/images/restaurants/cafe-hafa-vista.jpg'],
    description: 'Café en terrasses suspendues au-dessus du détroit, là où Marshan rencontre la mer. Msemen beurrés, jus pressés et une vue que tout Tanger vient chercher.',
    tags: ['Vue mer', 'Petit-déjeuner', 'Calme'],
    menu: [
      { name: 'Msemen au miel', desc: 'Crêpe feuilletée tiède, miel d’oranger et beurre fondu', price: '18 DH', cat: 'Brunch', star: true },
      { name: 'Baghrir mille trous', desc: 'Nappé de miel-beurre, parfumé à l’anis', price: '18 DH', cat: 'Brunch' },
      { name: 'Bissara du matin', desc: 'Purée de fèves à l’huile d’olive et cumin', price: '20 DH', cat: 'Brunch' },
      { name: 'Œufs au khlii', desc: 'Œufs au plat à la viande séchée confite, pain beldi', price: '35 DH', cat: 'Brunch', star: true },
      { name: 'Assiette de fruits frais', desc: 'Fruits du marché central, menthe ciselée', price: '30 DH', cat: 'Desserts' },
      { name: 'Thé à la menthe', desc: 'Le rituel de la maison, face au détroit', price: '15 DH', cat: 'Boissons', star: true },
      { name: 'Jus d’avocat-amande', desc: 'Onctueux, lait d’amande et miel', price: '25 DH', cat: 'Boissons' },
    ],
    reviewList: [
      { name: 'Hassan E.', rating: 5, text: 'Le plus beau panorama de Tanger, thé parfait.', date: 'il y a 1 j' },
      { name: 'Emma W.', rating: 5, text: 'Petit-déjeuner face au détroit, magique.', date: 'il y a 3 j' },
      { name: 'Nabil C.', rating: 4, text: 'Très fréquenté le week-end, venez tôt.', date: 'il y a 1 sem.' },
    ],
  },
  {
    id: 't12', hours: '12:00–23:00', name: 'La Sqala de Tanger', cuisine: 'Marocaine · Poisson', area: 'Kasbah · Remparts',
    rating: 4.2, reviews: 156, price: '€€€', priceLevel: 3, offer: null, availableTonight: true,
    slots: ['19:00','20:30','21:30'], slotsFull: ['20:00'], x: 300, y: 162, from: '#7a6a4a', to: '#4e4330',
    img: '/images/restaurants/sqala-tanger.jpg',
    photos: ['/images/restaurants/sqala-tanger.jpg'],
    description: 'Table perchée sur les remparts face au détroit, entre canons d’époque et oud en soirée. La pastilla aux fruits de mer et le tajine de poisson y règnent depuis trois générations.',
    tags: ['Traditionnel', 'Poisson frais', 'Musique live'],
    menu: [
      { name: 'Salade de la Sqala', desc: 'Poivrons grillés, tomates et œufs de caille', price: '45 DH', cat: 'Entrées' },
      { name: 'Pastilla aux fruits de mer', desc: 'Calamars, crevettes et vermicelles, feuille croustillante', price: '130 DH', cat: 'Plats', star: true },
      { name: 'Tajine de poisson', desc: 'Poisson du jour, chermoula, pommes de terre et olives', price: '110 DH', cat: 'Plats', star: true },
      { name: 'Couscous aux fruits de mer', desc: 'Semoule fine, gambas et moules, bouillon safrané', price: '125 DH', cat: 'Plats' },
      { name: 'Brochettes d’espadon', desc: 'Marinées à la chermoula, grillées au charbon', price: '115 DH', cat: 'Plats' },
      { name: 'Mhalbi à la fleur d’oranger', desc: 'Crème de riz fraîche, cannelle', price: '25 DH', cat: 'Desserts' },
      { name: 'Thé à la menthe des remparts', desc: 'Servi au plateau de cuivre, au son du oud', price: '20 DH', cat: 'Boissons' },
    ],
    reviewList: [
      { name: 'Fouad Z.', rating: 4, text: 'Cadre historique unique, pastilla aux fruits de mer mémorable.', date: 'il y a 6 j' },
      { name: 'Camille R.', rating: 4, text: 'Le oud en soirée ajoute beaucoup de charme.', date: 'il y a 2 sem.' },
    ],
  },
  {
    id: 't13', hours: '07:30–19:30', name: 'Pâtisserie Al Andalus', cuisine: 'Pâtisserie · Salon de thé', area: 'Iberia',
    rating: 4.8, reviews: 673, price: '€', priceLevel: 1, offer: '-15%', offerDesc: 'Happy hour thé & pâtisseries (16h–18h)', availableTonight: false,
    slots: ['10:00','16:00','17:30'], slotsFull: ['16:30'], x: 180, y: 378, from: '#d9a23f', to: '#9a6e22',
    img: '/images/restaurants/patisserie-al-andalus.jpg',
    photos: ['/images/restaurants/patisserie-al-andalus.jpg'],
    description: 'Institution familiale d’Iberia où les plateaux de gâteaux d’amande embaument depuis trois générations. On y vient pour la pastilla au lait et le thé servi dans l’argenterie.',
    tags: ['Petit-déjeuner', 'Calme', 'Familial'],
    menu: [
      { name: 'Briouates au miel', desc: 'Amandes grillées, miel pur et cannelle', price: '12 DH', cat: 'Pâtisseries', star: true },
      { name: 'Cornes de gazelle royales', desc: 'Pâte fine, amande et fleur d’oranger', price: '10 DH', cat: 'Pâtisseries', star: true },
      { name: 'Chebakia au sésame', desc: 'Croustillante, trempée au miel d’eucalyptus', price: '8 DH', cat: 'Pâtisseries' },
      { name: 'Pastilla au lait', desc: 'Feuilles croustillantes, crème à la fleur d’oranger, amandes', price: '35 DH', cat: 'Desserts', star: true },
      { name: 'Mhancha aux amandes', desc: 'Serpentin d’amandes, miel et cannelle', price: '15 DH', cat: 'Pâtisseries' },
      { name: 'Assortiment du salon (12 pièces)', desc: 'Sélection du jour à partager', price: '90 DH', cat: 'Pâtisseries' },
      { name: 'Thé à la menthe à l’ancienne', desc: 'Théière en argent, pignons offerts', price: '18 DH', cat: 'Boissons' },
      { name: 'Café aux épices', desc: 'Café noir à la cannelle et cardamome', price: '15 DH', cat: 'Boissons' },
    ],
    reviewList: [
      { name: 'Amina T.', rating: 5, text: 'Les meilleures cornes de gazelle de la ville, sans débat.', date: 'il y a 2 j' },
      { name: 'Driss H.', rating: 5, text: 'La pastilla au lait est un trésor. Service adorable.', date: 'il y a 1 sem.' },
      { name: 'Léa V.', rating: 4, text: 'Salon élégant, parfait pour une pause sucrée.', date: 'il y a 2 sem.' },
    ],
  },
  {
    id: 't14', hours: '19:00–00:00 · fermé le mardi', name: 'Le Détroit Grill', cuisine: 'Grillades · Viandes', area: 'Malabata',
    rating: 4.1, reviews: 98, price: '€€€', priceLevel: 3, offer: null, availableTonight: true,
    slots: ['20:00','21:00','22:30'], slotsFull: ['20:30','21:30'], x: 575, y: 352, from: '#8a4a2e', to: '#54301e',
    img: '/images/restaurants/detroit-grill.jpg',
    photos: ['/images/restaurants/detroit-grill.jpg'],
    description: 'Steakhouse en rooftop face aux lumières du détroit : viandes maturées sur place et braises d’olivier. Le carré d’agneau est taillé pour deux.',
    tags: ['Grillades', 'Vue mer', 'Rooftop', 'Chic'],
    menu: [
      { name: 'Carpaccio de bœuf', desc: 'Tranché minute, copeaux de parmesan, roquette', price: '85 DH', cat: 'Entrées' },
      { name: 'Entrecôte maturée (350 g)', desc: 'Maturation 30 jours, beurre aux herbes, frites maison', price: '220 DH', cat: 'Plats', star: true },
      { name: 'Carré d’agneau pour deux', desc: 'Rôti aux braises d’olivier, jus au romarin', price: '320 DH', cat: 'Plats', star: true },
      { name: 'Brochettes du détroit', desc: 'Trio bœuf, agneau et poulet mariné', price: '120 DH', cat: 'Plats' },
      { name: 'Burger Détroit', desc: 'Bœuf maturé haché main, cheddar affiné, pain brioché', price: '95 DH', cat: 'Plats' },
      { name: 'Fondant au chocolat', desc: 'Cœur coulant, glace vanille', price: '50 DH', cat: 'Desserts', star: true },
      { name: 'Jus de raisin pétillant', desc: 'Servi très frais en carafe', price: '35 DH', cat: 'Boissons' },
    ],
    reviewList: [
      { name: 'Othmane J.', rating: 4, text: 'Entrecôte parfaitement maturée, belle vue de nuit.', date: 'il y a 5 j' },
      { name: 'Sophie N.', rating: 4, text: 'Carré d’agneau généreux, addition à prévoir.', date: 'il y a 2 sem.' },
    ],
  },
  {
    id: 't15', hours: '11:30–16:00 · déjeuner uniquement', name: 'Dar Seksou', cuisine: 'Marocaine · Couscous', area: 'Médina',
    rating: 4.5, reviews: 451, price: '€', priceLevel: 1, offer: '-10%', offerDesc: 'Offre étudiants FSTT : −10% sur présentation de la carte', availableTonight: false,
    slots: ['12:00','12:30','13:30'], slotsFull: ['13:00'], x: 288, y: 308, from: '#c98f3a', to: '#8a5f24',
    img: '/images/restaurants/dar-seksou.jpg',
    photos: ['/images/restaurants/dar-seksou.jpg'],
    description: 'Petite maison de la Médina entièrement dédiée au couscous, roulé à la main chaque matin. Le vendredi, la file s’étire jusqu’à la place — on comprend pourquoi.',
    tags: ['Cuisine locale', 'Traditionnel', 'Convivial', 'Familial'],
    menu: [
      { name: 'Harira express', desc: 'Le bol du midi, citron et dattes', price: '25 DH', cat: 'Entrées' },
      { name: 'Felfla grillée', desc: 'Salade de poivrons grillés à l’ail', price: '25 DH', cat: 'Entrées' },
      { name: 'Couscous du vendredi aux sept légumes', desc: 'Le classique roulé main, bouillon parfumé', price: '85 DH', cat: 'Plats', star: true },
      { name: 'Couscous au poulet beldi', desc: 'Poulet fermier, oignons confits et raisins secs', price: '95 DH', cat: 'Plats', star: true },
      { name: 'Couscous tfaya d’agneau', desc: 'Agneau fondant, tfaya caramélisée et amandes', price: '115 DH', cat: 'Plats', star: true },
      { name: 'Couscous végétarien', desc: 'Sept légumes de saison, pois chiches et bouillon léger', price: '70 DH', cat: 'Plats' },
      { name: 'Seffa medfouna aux amandes', desc: 'Vermicelles sucrés-salés, cannelle et amandes', price: '60 DH', cat: 'Plats' },
      { name: 'Lben & thé à la menthe', desc: 'Babeurre fermier ou thé, pour accompagner', price: '12 DH', cat: 'Boissons' },
    ],
    reviewList: [
      { name: 'Brahim Q.', rating: 5, text: 'Le couscous du vendredi comme chez ma grand-mère.', date: 'il y a 1 j' },
      { name: 'Élodie P.', rating: 4, text: 'Authentique et délicieux, prix mini.', date: 'il y a 1 sem.' },
      { name: 'Walid M.', rating: 5, text: 'La tfaya est exceptionnelle. Arrivez avant 13h !', date: 'il y a 3 sem.' },
    ],
  },
  {
    id: 't16', hours: '09:00–17:00', name: 'Casa Playa', cuisine: 'Méditerranéenne · Brunch', area: 'Corniche',
    rating: 3.9, reviews: 67, price: '€€', priceLevel: 2, offer: 'Brunch', offerDesc: 'Brunch à volonté le dimanche (149 DH)', availableTonight: false,
    slots: ['10:00','11:30','13:00'], slotsFull: ['12:00','12:30'], x: 526, y: 148, from: '#9aa55a', to: '#6c7838',
    img: '/images/restaurants/casa-playa.jpg',
    photos: ['/images/restaurants/casa-playa.jpg'],
    description: 'Paillote chic sur la Corniche, pieds nus dans le sable et grandes tablées blanches. Le brunch à volonté du dimanche et les bowls ensoleillés font sa réputation montante.',
    tags: ['Vue mer', 'Lounge', 'Healthy', 'Romantique'],
    menu: [
      { name: 'Açaï bowl', desc: 'Açaï, granola maison, fruits frais et miel', price: '65 DH', cat: 'Brunch' },
      { name: 'Avocado toast', desc: 'Pain au levain, avocat, œuf poché et dukkah', price: '55 DH', cat: 'Brunch' },
      { name: 'Pancakes ricotta-citron', desc: 'Moelleux, sirop d’érable et zestes', price: '60 DH', cat: 'Brunch', star: true },
      { name: 'Salade Casa Playa', desc: 'Quinoa, feta, grenade et menthe fraîche', price: '75 DH', cat: 'Plats', star: true },
      { name: 'Wrap au poulet grillé', desc: 'Crudités croquantes, sauce yaourt aux herbes', price: '70 DH', cat: 'Plats' },
      { name: 'Cheesecake fruits rouges', desc: 'Léger, coulis de saison', price: '45 DH', cat: 'Desserts' },
      { name: 'Smoothie coco-mangue', desc: 'Mangue mûre, lait de coco, citron vert', price: '40 DH', cat: 'Boissons', star: true },
    ],
    reviewList: [
      { name: 'Oumaima F.', rating: 4, text: 'Brunch du dimanche très complet, cadre superbe.', date: 'il y a 4 j' },
      { name: 'Marc L.', rating: 3, text: 'Joli spot mais service débordé en haute saison.', date: 'il y a 2 sem.' },
    ],
  },
]
